# Generated by Django 6.0.1 on 2026-01-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='z.B. lucas-falkowsky', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('label', models.CharField(help_text='z.B. Fullstack Developer', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('summary', models.TextField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(default='DE', max_length=10)),
                ('primary_color', models.CharField(default='#171D26', max_length=7)),
                ('accent_color', models.CharField(default='#FF5959', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('study_type', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Development, Sprachen, etc.', max_length=100)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='cv_app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, help_text='z.B. 80% oder leer lassen für Tags', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cv_app.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.CharField(help_text='z.B. 2023-01', max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20, null=True)),
                ('current', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('tech_stack', models.CharField(blank=True, help_text='Kommagetrennt', max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='cv_app.cv')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
