# Generated by Django 6.0.1 on 2026-01-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.TextField(blank=True, default='', verbose_name='Erfahrung & Highlights'),
        ),
    ]
