services:
  cv-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-manager
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - cv_data:/app/backend/data
      - cv_media:/app/backend/media

  cv-manager-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - cv-manager
    volumes:
      - cv_media:/app/backend/media

volumes:
  cv_data:
  cv_media: